### ISSUE TITLE
Abstracting away p′ and the equation of state

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#23]
@thabbott suggested I take a look at section 2 and see if we can abstract away the calculation of p′ and the equation of state as they might depend on terms we don't know.

Just starting to think about this, and it seem like it'll be easy for the dry ideal gas law, but had some questions as I'm not familiar with atmospheric thermodynamics.

1. For atmospheric modeling, you always want to get an expression for the specific entropy? Presumably if you cannot obtain such an expression, you cannot use that equation of state.

2. The entropy of an ideal gas is given by the Sackur-Tetrode equation (probably not useful here) while the specific entropy defined in the notes is the change in entropy for an ideal gas undergoing some process. Would it be useful to denote it as Δs? Maybe not if it's universally understood that we always talk about entropy changes.

3. Will p′ ever depend on any other prognostic variables besides ρ′ and (ρs)′? I suppose for a moist atmosphere, water vapor might be a prognostic variable too?

4. Seems that `c_p` and `c_v` are introduced in the definition of specific entropy. Do we imagine having other equations of state that do not have a `c_p` or `c_v`, or have a wildly different definition of specific entropy? If so, we'll have to abstract away a lot of terms, mostly p′ probably.

Might be helpful to at least consider the dry ideal gas and moist ideal gas cases to see what abstraction would work best.

Are there other equations of state we should consider when designing this abstraction? @thabbott suggested maybe ideal gas for 2+ condensible components, but also maybe an equation of state where the ideal gas law breaks down?

Maybe we should just stick to the dry and moist ideal gases for now, and just refactor to support exotic equations of state when we want to implement them.

**Comment by thabbott** [comment]
1. Not necessarily---there are other choices that also make for good prognostic thermodynamic variables (potential temperature, dry/moist static energy, etc.) Specific entropy appears a lot in our notes because that's what we decided to use as our prognostic variable.

1. I'm not sure I understand this question---the entropy $s$ in the notes is defined as the sum of a reference entropy $s_0 = s(T_0, p_0)$ and a change relative to that reference state, so it's not itself just a change in entropy. We could write everything in terms of just the change relative to the reference state, but I think replacing $s$ with $\Delta s$ everywhere would make the notation clunky.

1. Yes, most likely-- that's why I want to try to abstract away the relationship between $p'$ and other prognostic variables as much as possible.

1. A gas will always have a $c_p$ and a $c_v$, but we might want to make them composition-dependent at some point.

FYI, I just pushed some updated notes to [thabbott/acoustic-time-step](/thabbott/JULES.jl/tree/thabbott/acoustic-time-step) with an algorithm that allows for a bit more flexibility, but the notation is terrible so I wouldn't bother looking at it yet.
