### ISSUE TITLE
Reference pressures

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#29]
Should the reference surface pressure (e.g. used in the definition of potential temperature) and the reference pressure in the equation of state always be the same?

If so, then it would make sense to keep track of the reference surface pressure in the `IdealGas` struct.

**Comment by natgeo-wong** [comment]
Should get Tristan to confirm, but since currently the model is assumed to have a uniform surface without any forcings I think it can be assumed to be the same.  Or I might be completely wrong haha.

But if we want to expand this to other scenarios this might be a moot point, so perhaps keep it where it is for now?

**Comment by ali-ramadhan** [comment]
Yeah I'm not sure why you'd pick them to be different. But sometimes I see the reference state is chosen to be the triple point of water or something, but maybe this isn't a thing in atmospheric science.

> But if we want to expand this to other scenarios this might be a moot point, so perhaps keep it where it is for now?

Good point. If there's a use case where you'd want them to be different we should support that.

**Comment by thabbott** [comment]
You can pick any reference state you want for the eos (by which I assume
you mean s(p,T)?)---as long as you don't change it over the course of a
model run it shouldn't matter. I'm not sure what the reference surface
pressure you're talking about is, though. Do you just mean the surface
pressure you pick to initialize the model fields? If so that's independent
of the eos reference state (and shouldn't be stored with it).

**Comment by ali-ramadhan** [comment]
Ah cool, they're separate in PR #27 so I'll keep them like that.

> I'm not sure what the reference surface pressure you're talking about is, though. Do you just mean the surface pressure you pick to initialize the model fields? If so that's independent of the eos reference state (and shouldn't be stored with it).

I guess so. I assume this is also the surface pressure that shows up if you want to diagnose potential temperature or the Exner function. Might be more relevant when running with modified potential temperature rather than entropy.

**Comment by thabbott** [comment]
The reference pressure you use to calculate potential temperatures can also
be anything you want it to be---similar to the reference state you pick
when  you define entropy.
