### ISSUE TITLE
Viscosity μ (Pa·s) vs. kinematic viscosity ν (m²/s)?

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#52]
Just to confirm, we want to use kinematic viscosity ν (m²/s)?

it seems that the atmospheric modeling community always means kinemtic viscosity (m²/s) when they say "viscosity".

**Comment by thabbott** [comment]
Both are used frequently, but you should be able to figure out which is correct for a given equation by looking at the units (the two only differ by a factor of density).

**Comment by ali-ramadhan** [comment]
True. I guess I'm wondering if models tend to stick to one or the other (or support both for different things).

In particular, I'm wondering about this as I think about how to share turbulence closures between compressible and incompressible models.

**Comment by thabbott** [comment]
I guess I'm a little confused about what you mean by "support", maybe this will help: the way that I've seen models incorporate turbulence closures is by including a generic stress tensor (so that e.g. the momentum equation looks like

<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{300}&space;\frac{\partial&space;\rho&space;u_i}{\partial&space;t}&space;&plus;&space;\partial_j&space;\left(\rho&space;u_i&space;u_j&space;&plus;\tau_{ij}&space;\right)&space;=&space;-&space;\partial_i&space;p&space;-&space;\rho&space;g&space;\delta_{i3}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{300}&space;\frac{\partial&space;\rho&space;u_i}{\partial&space;t}&space;&plus;&space;\partial_j&space;\left(\rho&space;u_i&space;u_j&space;&plus;\tau_{ij}&space;\right)&space;=&space;-&space;\partial_i&space;p&space;-&space;\rho&space;g&space;\delta_{i3}" title="\frac{\partial \rho u_i}{\partial t} + \partial_j \left(\rho u_i u_j +\tau_{ij} \right) = - \partial_i p - \rho g \delta_{i3}" width=50%/></a>

where τ is a stress tensor calculated by the turbulence closure.

One option for a turbulence "closure" is just compressible DNS, in which case you can calculate the stress tensor τ from the dynamic viscosity μ as

<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{300}&space;\tau_{ij}&space;=&space;-\mu&space;\left&space;(&space;\partial_i&space;u_j&space;&plus;&space;\partial_j&space;u_i&space;-&space;\frac{2}{3}&space;\delta_{ij}&space;\partial_i&space;u_i&space;\right)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{300}&space;\tau_{ij}&space;=&space;-\mu&space;\left&space;(&space;\partial_i&space;u_j&space;&plus;&space;\partial_j&space;u_i&space;-&space;\frac{2}{3}&space;\delta_{ij}&space;\partial_i&space;u_i&space;\right)" title="\tau_{ij} = -\mu \left ( \partial_i u_j + \partial_j u_i - \frac{2}{3} \delta_{ij} \partial_i u_i \right)" width=40%/></a>

In this case, we might ask the user to provide an expression for μ as a function of the thermodynamic state of the fluid. But to me it makes more sense to support that definition within this specific turbulence closure than to support it throughout the model as a whole.

**Comment by ali-ramadhan** [comment]
Thanks for the explanation. I guess it makes more sense to support a constant kinematic viscosity ν as μ generally depends strongly on temperature T and so constant viscosity μ might not make much sense in an atmosphere where the density (and presumably temperature) varies significantly.

I was thinking it would be simpler to use μ in `compressible_operators.jl` but then you'd have to define a
```julia
μ(i, j, k, grid, ρ, ν) = ν * ρ[i, j, k]
```
at the very least.
