### ISSUE TITLE
Worth retaining modified potential temperature as a prognostic variable?

### ISSUE THREAD

**Issue by thabbott** [thabbott/JULES.jl#54]
It's convenient if you want to work with dry air + dilute water vapor but doesn't extend in a particularly straightforward way to other situations, so it's unclear to me whether it's worth keeping it in JULES (as opposed to just developing the model with entropy for now). Thoughts?

**Comment by ali-ramadhan** [comment]
I don't have any strong opinions here, mainly because I'm not super familiar with atmospheric models.

I'm happy to move forward with just entropy for now, especially if we're gonna switch to an equation set closer to Satoh (2003). It might be nice to keep a second thermodynamic variable to be able to develop an abstraction for switching between different thermodynamic variables. Would regular potential temperature work as a second choice here? Or maybe something else like internal energy.

I guess it would be good to also support the most popular thermodynamic variable (if there is such a thing) as it might be easier to capture new users that way?
